// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUn9KfLCP7PlNHf0dqtgn-5s6kEFE3OzU',
    appId: '1:705312277210:web:5eab1fa20621fcc30f9be3',
    messagingSenderId: '705312277210',
    projectId: 'taller3flutter-42715',
    authDomain: 'taller3flutter-42715.firebaseapp.com',
    storageBucket: 'taller3flutter-42715.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMl_RPrNnCfMo5pvq6zRViV1s2ismye2w',
    appId: '1:705312277210:android:ed14e5b8ebe63af60f9be3',
    messagingSenderId: '705312277210',
    projectId: 'taller3flutter-42715',
    storageBucket: 'taller3flutter-42715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5O4mOBNovJ3MPOqGkYi-3ARQo2g7dsOw',
    appId: '1:705312277210:ios:be234f28bd1b98d40f9be3',
    messagingSenderId: '705312277210',
    projectId: 'taller3flutter-42715',
    storageBucket: 'taller3flutter-42715.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaller3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5O4mOBNovJ3MPOqGkYi-3ARQo2g7dsOw',
    appId: '1:705312277210:ios:be234f28bd1b98d40f9be3',
    messagingSenderId: '705312277210',
    projectId: 'taller3flutter-42715',
    storageBucket: 'taller3flutter-42715.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaller3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUn9KfLCP7PlNHf0dqtgn-5s6kEFE3OzU',
    appId: '1:705312277210:web:0aefa7732ba45c3c0f9be3',
    messagingSenderId: '705312277210',
    projectId: 'taller3flutter-42715',
    authDomain: 'taller3flutter-42715.firebaseapp.com',
    storageBucket: 'taller3flutter-42715.firebasestorage.app',
  );
}
